using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudentPortal.Models;
using System.ComponentModel.DataAnnotations;

namespace StudentPortal.Pages.Admin
{
    [Authorize(Roles = "Admin,Staff")]
    public class ManageCoursesModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public List<Course> Courses { get; set; } = new();

        // Bind the new course input
        [BindProperty]
        public NewCourseInputModel NewCourse { get; set; }

        public class NewCourseInputModel
        {
            [Required]
            [StringLength(20)]
            public string CourseCode { get; set; }

            [Required]
            [StringLength(100)]
            public string CourseName { get; set; }

            public string Description { get; set; }

            [Required]
            public int CreditHours { get; set; }

            [Required]
            [StringLength(100)]
            public string Department { get; set; }

            [Required]
            public int CourseCost { get; set; }
        }

        public ManageCoursesModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task OnGetAsync()
        {
            Courses = await _context.Courses.ToListAsync();
        }

        public async Task<IActionResult> OnPostAddCourseAsync()
        {
            if (!ModelState.IsValid)
            {
                Courses = await _context.Courses.ToListAsync();
                return Page();
            }

            // Create a new course using the input values
            var course = new Course
            {
                CourseCode = NewCourse.CourseCode,
                CourseName = NewCourse.CourseName,
                Description = NewCourse.Description,
                CreditHours = NewCourse.CreditHours,
                Department = NewCourse.Department,
                CourseCost = NewCourse.CourseCost,
                CreatedAt = DateTime.Now,
                // CreatedAt is generated by the database
            };

            _context.Courses.Add(course);
            await _context.SaveChangesAsync();

            // Redirect to GET to refresh the courses list and clear the form
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteCourseAsync(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }

            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();

            return RedirectToPage(); // Refresh the page after deletion
        }

    }
}
